### ISSUE TITLE
ict pinout

### ISSUE THREAD

**Issue by geniomau** [caiguanhao/ict#2]
Hello, You would get the pinout of the ict I would like you to have the p70 model. But I believe that another one will do because I tried several pins and I didn't get a result.
Could you help me please. Thank you
![camera_capture (1)](https://user-images.githubusercontent.com/12689489/120063013-78f72b80-c03b-11eb-9904-5894d0c9800b.jpg)
![camera_capture (2)](https://user-images.githubusercontent.com/12689489/120063015-7a285880-c03b-11eb-92aa-fb5d6ca2cba7.jpg)
![camera_capture](https://user-images.githubusercontent.com/12689489/120063017-7ac0ef00-c03b-11eb-8199-cd7a8fefe812.jpg)

**Comment by caiguanhao** [comment]
Have you read the manual for the device? If you don't have one, I can get one for you.

**Comment by geniomau** [comment]
Thanks for the answer. I got this used device as a gift, so I don't have the manual. I searched the internet but didn't find it. Thank you very much if you get a manual that helps, I would also like to try to calibrate it because it is not accepting some notes.
![camera_capture (4)](https://user-images.githubusercontent.com/12689489/120109183-bbedf780-c13e-11eb-81ac-dafea65839c7.jpg)
![camera_capture (3)](https://user-images.githubusercontent.com/12689489/120109188-bdb7bb00-c13e-11eb-85d9-3fecfdf98957.jpg)

**Comment by caiguanhao** [comment]
Have you googled yet? I googled "ICT p70" and I got this: http://www.dvbvending.net.ua/files/manual/P_Series_P70-P77-P85.pdf

**Comment by geniomau** [comment]
Yes, I searched and I already had this manual but I didn't find a valid reference, as in the last image the rx found out of the manual's reference, but I didn't find the tx even sending a signal to all the pins. But thanks.

**Comment by caiguanhao** [comment]
Sorry, I only got manuals like this. If you have further questions, you may need to contact your local ICT customer service.
